name: release-new
on:
  workflow_dispatch:
    inputs:
      wkhtmltopdf_ref:
        description: 'Branch/Tag to use from the ismxilxrif/wkhtmltopdf repository'
        required: true
      packaging_release:
        description: 'Release to create in ismxilxrif/packaging repository'
        required: true
      packaging_iteration:
        description: 'Iteration (useful for tagged releases)'
        default: '1'
        required: true

jobs:
  docker:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package_target:
          - noble-amd64
          - noble-arm64
          - noble-ppc64el
          - trixie-amd64
          - trixie-arm64
          - trixie-ppc64el
          - archlinux-amd64
          - almalinux10-x86_64
          - almalinux10-aarch64
          - almalinux10-ppc64le
          - fedora42-x86_64
          - fedora42-aarch64
          - fedora42-ppc64le
          - fedora43-x86_64
          - fedora43-aarch64
          - fedora43-ppc64le
      fail-fast: false
    steps:
      - name: configure docker
        run:  |
          echo '{ "experimental": true }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
      - name: checkout packaging
        uses: actions/checkout@v4.1.4
        with:
          path: packaging
      - name: checkout wkhtmltopdf with submodules
        uses: actions/checkout@v4.1.4
        with:
          repository: ismxilxrif/wkhtmltopdf
          path: wkhtmltopdf
          submodules: true
          ref: ${{ github.event.inputs.wkhtmltopdf_ref }}
      - name: build
        run: cd packaging && python3 ./build package-docker --clean --iteration ${{ github.event.inputs.packaging_iteration }} ${{ matrix.package_target }} ../wkhtmltopdf
      - uses: softprops/action-gh-release@v2.0.5
        with:
          name: ${{ github.event.inputs.packaging_release }}
          tag_name: ${{ github.event.inputs.packaging_release }}-${{ github.event.inputs.packaging_iteration }}
          target_commitish: ${{ github.sha }}
          files: "packaging/targets/wkhtmltox*.*"
          fail_on_unmatched_files: false
          draft: true
          body: All packages were built and uploaded automatically as a part of [this run](${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}), using this [wkhtmltopdf branch/tag](https://github.com/ismxilxrif/wkhtmltopdf/tree/${{ github.event.inputs.wkhtmltopdf_ref }}).
